# Generated by Django 4.1 on 2022-08-27 10:25

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntiqueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Url')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='AntiqueLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('latitude', models.CharField(max_length=255, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=255, verbose_name='Longitude')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city', verbose_name='City')),
            ],
        ),
        migrations.CreateModel(
            name='Antique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('overview', models.CharField(max_length=255, verbose_name='Name')),
                ('description', ckeditor.fields.RichTextField(max_length=255, verbose_name='Name')),
                ('religion', models.CharField(max_length=255, verbose_name='Religion')),
                ('origin', models.CharField(max_length=255, verbose_name='Origin')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Main Image')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location', to='antiques.antiquelocation')),
                ('type_of_build', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='antiques.antiquetype', verbose_name='Type Of Build')),
            ],
        ),
    ]
