# Generated by Django 4.1 on 2022-08-27 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiques', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='antique',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 8, 27, 11, 24, 24, 726096, tzinfo=datetime.timezone.utc), verbose_name='Timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='antique',
            name='updaated',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 8, 27, 11, 24, 35, 625037, tzinfo=datetime.timezone.utc), verbose_name='Updated'),
            preserve_default=False,
        ),
    ]
