# Generated by Django 4.1 on 2022-08-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiques', '0002_antique_timestamp_antique_updaated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antique',
            name='updaated',
        ),
        migrations.AddField(
            model_name='antique',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
    ]
