# Generated by Django 4.1 on 2022-09-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiques', '0003_remove_antique_updaated_antique_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='antique',
            name='uid',
            field=models.CharField(default=1, max_length=255, verbose_name='Unique ID'),
            preserve_default=False,
        ),
    ]
