# Generated by Django 4.1 on 2022-09-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiques', '0007_reference_antique'),
    ]

    operations = [
        migrations.AddField(
            model_name='antiquelocation',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Place'),
        ),
    ]
