# Generated by Django 4.1 on 2022-09-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiques', '0008_antiquelocation_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antique',
            name='end_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='antique',
            name='start_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Start Date'),
        ),
    ]
