# Generated by Django 4.1 on 2022-08-19 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageField',
            new_name='UploadedImage',
        ),
    ]
